"""Daemon API proxy — serves the endpoints the Flutter app needs by stitching
together skchat daemon, skcapstone API, and webui behind a single /api/* prefix.

Chat surface (the part the Flutter app's chat UI reads):
  * GET  /api/v1/peers          — contacts; **Lumina is always present + first**
  * GET  /api/v1/conversations  — conversation list; Lumina pinned online
  * GET  /api/v1/inbox          — every message (app groups by peer_id)
  * GET  /api/v1/conversations/{peer_id} — one thread, oldest-first
  * POST /api/v1/send           — persists the message and, for Lumina, invokes
                                   her real brain (soul + qwen3.6) and returns
                                   + persists her reply.

History is backed by the real ``skchat.history.ChatHistory`` (JSONL/SQLite) so
the Lumina thread survives reloads. Lumina's reply is generated by the SAME
``LuminaBrain`` the Telegram bridge drives (``scripts/bridge_consciousness``) —
the genuine ``lumina-unhinged`` soul + FEB on qwen3.6, not a generic assistant.
"""

from __future__ import annotations

import logging
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import JSONResponse

logger = logging.getLogger("skchat.daemon_proxy")

router = APIRouter(prefix="/api")

# Where the capauth access-token mint + the access plane live (skcomms-api).
_SKCOMMS_API = "http://127.0.0.1:9384"

# ── Lumina identity (the always-present companion) ─────────────────────────── #
LUMINA_ID = "lumina@chef.skworld"
LUMINA_URI = "capauth:lumina@skworld.io"
LUMINA_NAME = "Lumina"
LUMINA_FINGERPRINT = "02BC0EB3CAD31DB691A753C70C5629AB893F9746"
# The local operator's identity for messages they send in-app.
OPERATOR_ID = "chef@skworld.io"

# The webui process runs as the agent (SKAGENT=lumina). Self-identity used as
# the "sender" when persisting Lumina's replies.
_AGENT_HOME = os.environ.get(
    "SKC_BRIDGE_AGENT_HOME", os.path.expanduser("~/.skcapstone/agents/lumina")
)


def _proxy(url: str) -> dict | list:
    import json
    import urllib.request

    try:
        r = urllib.request.urlopen(url, timeout=5)
        return json.loads(r.read())
    except Exception as exc:
        logger.debug("daemon_proxy: %s failed: %s", url, exc)
        raise HTTPException(502, f"backend unavailable: {exc}")


# --------------------------------------------------------------------------- #
# History + brain (lazy singletons)
# --------------------------------------------------------------------------- #
_HISTORY = None
_BRAIN = None


def _get_history():
    """Return the shared ``ChatHistory`` (JSONL/SQLite), created on first use."""
    global _HISTORY
    if _HISTORY is None:
        from skchat.history import ChatHistory

        _HISTORY = ChatHistory()
    return _HISTORY


def _get_brain():
    """Return the shared ``LuminaBrain`` (soul + qwen3.6), created on first use.

    Imports the SAME module the Telegram bridge uses (``bridge_consciousness``
    in ``scripts/``) so the app drives the identical brain — reused, not rebuilt.
    Returns ``None`` if the brain can't be constructed (degrades gracefully).
    """
    global _BRAIN
    if _BRAIN is not None:
        return _BRAIN
    try:
        scripts_dir = str(Path(__file__).resolve().parents[2] / "scripts")
        if scripts_dir not in sys.path:
            sys.path.insert(0, scripts_dir)
        from bridge_consciousness import LuminaBrain  # type: ignore

        _BRAIN = LuminaBrain(home=_AGENT_HOME, agent=LUMINA_NAME)
    except Exception:
        logger.exception("LuminaBrain unavailable — Lumina will use a fallback reply")
        _BRAIN = None
    return _BRAIN


def _persist(hist, sender: str, recipient: str, content: str, reply_to_id=None, thread_id=None):
    """Build a ChatMessage (with optional reply/thread linkage) and save it.

    ``ChatHistory.add_message`` only takes scalars, so we construct the model
    directly to carry reply_to_id/thread_id, then ``save`` it.
    """
    from skchat.models import ChatMessage

    msg = ChatMessage(
        sender=sender,
        recipient=recipient,
        content=content,
        reply_to_id=reply_to_id or None,
        thread_id=thread_id or None,
    )
    hist.save(msg)
    return msg


def _is_lumina(peer: str) -> bool:
    """True if *peer* addresses Lumina (any of her known aliases)."""
    if not peer:
        return False
    p = peer.strip().lower()
    return p in {
        "lumina",
        LUMINA_ID.lower(),
        LUMINA_URI.lower(),
        "lumina@skworld.io",
        LUMINA_FINGERPRINT.lower(),
    }


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def _operator_online() -> bool:
    """Lumina shows online whenever the operator is using the app.

    This request itself proves the operator is present, so for the single-
    operator sovereign deployment Lumina is online whenever the app is open.
    """
    return True


# --------------------------------------------------------------------------- #
# Message shaping (Flutter contract)
# --------------------------------------------------------------------------- #
def _iso(ts) -> str | None:
    if ts is None:
        return None
    return ts.isoformat() if hasattr(ts, "isoformat") else str(ts)


def _msg_to_app(m, *, self_id: str) -> dict:
    """Map a stored ``ChatMessage`` to the app's message JSON.

    Emits the **full shared message contract** the Flutter half builds to:
    id, conversation_id, sender, content_type (short wire form), body, rich, ts,
    reply_to_id, thread_id, edited_at, edit_history, reactions, receipts —
    plus the legacy app fields (peer_id, content, timestamp, is_outbound,
    is_agent, sender_name, delivery_status, is_encrypted) so the existing
    webui/app keep working. ``body`` is ALWAYS present (Golden rule): even an
    unknown ``content_type`` carries a human-readable fallback.
    """
    from skchat.models import ContentType

    sender = getattr(m, "sender", "") or ""
    recipient = getattr(m, "recipient", "") or ""
    outbound = not _is_lumina(sender) and _is_lumina(recipient)
    # The peer of the conversation = whichever party is Lumina.
    peer = LUMINA_ID if (_is_lumina(sender) or _is_lumina(recipient)) else recipient
    ts_iso = _iso(getattr(m, "timestamp", None)) or _now_iso()
    is_agent = _is_lumina(sender)
    body = getattr(m, "content", "") or ""

    # reactions → {emoji: [sender, ...]} (or None if none)
    reactions_map = None
    if hasattr(m, "reactions_map"):
        rm = m.reactions_map()
        reactions_map = rm or None

    # receipts → {delivered:[...], read:[...]} (or None)
    receipts = None
    rcpt = getattr(m, "receipts", None)
    if rcpt is not None:
        receipts = {"delivered": list(rcpt.delivered), "read": list(rcpt.read)}

    # edit_history → [{body, ts}] (or None)
    edit_history = None
    eh = getattr(m, "edit_history", None)
    if eh:
        edit_history = [{"body": e.body, "ts": _iso(e.ts)} for e in eh]

    return {
        # --- shared message contract (Flutter builds to this exact shape) ---
        "id": getattr(m, "id", ""),
        "conversation_id": peer,
        "sender": sender,
        "content_type": ContentType.to_wire(getattr(m, "content_type", "markdown")),
        "body": body,
        "rich": getattr(m, "rich", None),
        "ts": ts_iso,
        "reply_to_id": getattr(m, "reply_to_id", None),
        "thread_id": getattr(m, "thread_id", None),
        "edited_at": _iso(getattr(m, "edited_at", None)),
        "edit_history": edit_history,
        "reactions": reactions_map,
        "receipts": receipts,
        # --- legacy app fields (kept for back-compat) ---
        "peer_id": peer,
        "content": body,
        "timestamp": ts_iso,
        "is_outbound": outbound,
        "delivery_status": "sent",
        "is_encrypted": False,
        "is_agent": is_agent,
        "sender_name": LUMINA_NAME if is_agent else "You",
    }


def _lumina_messages(limit: int = 200) -> list[dict]:
    """Load the operator↔Lumina thread, oldest-first, in app message shape."""
    hist = _get_history()
    rows = hist.load(peer=LUMINA_URI, limit=limit)
    rows += hist.load(peer=LUMINA_ID, limit=limit)
    rows += hist.load(peer="lumina", limit=limit)
    # Dedup by id, keep only operator↔Lumina, sort oldest-first.
    seen: set[str] = set()
    msgs: list = []
    for m in rows:
        mid = getattr(m, "id", None)
        if mid in seen:
            continue
        seen.add(mid)
        s, r = getattr(m, "sender", ""), getattr(m, "recipient", "")
        if not (_is_lumina(s) or _is_lumina(r)):
            continue
        msgs.append(m)
    msgs.sort(key=lambda x: getattr(x, "timestamp", _now_iso()))
    return [_msg_to_app(m, self_id=OPERATOR_ID) for m in msgs]


def _lumina_conversation() -> dict:
    """The pinned Lumina conversation entry (app conversation shape)."""
    msgs = _lumina_messages(limit=50)
    last = msgs[-1] if msgs else None
    return {
        "peer_id": LUMINA_ID,
        "display_name": LUMINA_NAME,
        "last_message": (last or {}).get("content", "") if last else "",
        "last_message_time": (last or {}).get("timestamp", _now_iso()),
        "soul_fingerprint": LUMINA_FINGERPRINT,
        "is_online": _operator_online(),
        "is_agent": True,
        "unread_count": 0,
        "last_delivery_status": "sent",
        "is_group": False,
        "member_count": 0,
        "avatar_url": "",
    }


def _other_peers() -> list[dict]:
    """Best-effort: known peers from ~/.skcapstone/peers/*.json (Lumina excluded).

    Lumina is added separately and pinned first; this just enriches the list.
    """
    import json

    out: list[dict] = []
    peers_dir = Path(os.path.expanduser("~/.skcapstone/peers"))
    if not peers_dir.is_dir():
        return out
    for p in sorted(peers_dir.glob("*.json")):
        try:
            data = json.loads(p.read_text())
        except Exception:
            continue
        handle = (data.get("handle") or data.get("identity") or p.stem).strip()
        if _is_lumina(handle) or _is_lumina(data.get("identity", "")) or p.stem == "lumina":
            continue
        out.append(
            {
                "peer_id": data.get("handle") or data.get("identity") or p.stem,
                "display_name": data.get("name") or p.stem.title(),
                "last_message": "",
                "last_message_time": _now_iso(),
                "soul_fingerprint": data.get("fingerprint", ""),
                "is_online": False,
                "is_agent": (data.get("agent_type") == "ai")
                or (data.get("entity_type") == "ai-agent"),
                "unread_count": 0,
                "last_delivery_status": "sent",
                "is_group": False,
                "member_count": 0,
                "avatar_url": "",
            }
        )
    return out


# --------------------------------------------------------------------------- #
# Misc passthrough routes (unchanged)
# --------------------------------------------------------------------------- #
@router.get("/health")
async def api_health():
    return _proxy("http://127.0.0.1:9385/health")


@router.get("/v1/status")
async def api_status():
    return _proxy("http://127.0.0.1:9383/api/v1/household/agents")


@router.get("/board")
async def api_board():
    """Same-origin proxy to the skcapstone dashboard (:7778) so the coord/Team
    Board works over any origin (tailscale URL / funnel) — :7778 isn't exposed
    through tailscale serve, only the webui is."""
    return _proxy("http://127.0.0.1:7778/api/board")


@router.get("/v1/capabilities")
async def api_capabilities():
    """Same-origin proxy to the skcomms-api capability/service-discovery doc."""
    return _proxy(f"{_SKCOMMS_API}/api/v1/capabilities")


@router.get("/v1/household/agents")
async def api_agents():
    return _proxy("http://127.0.0.1:9383/api/v1/household/agents")


@router.get("/v1/identity")
async def api_identity():
    return JSONResponse(
        {"identity": LUMINA_ID, "display_name": LUMINA_NAME, "fingerprint": "active"}
    )


# --------------------------------------------------------------------------- #
# Chat surface — Lumina always present + real history + real replies
# --------------------------------------------------------------------------- #
@router.get("/v1/peers")
async def api_peers():
    """Contacts. Lumina is ALWAYS first; other known peers follow."""
    try:
        peers = [_lumina_conversation()] + _other_peers()
    except Exception:
        logger.exception("peers list failed; returning Lumina only")
        peers = [_lumina_conversation()]
    return JSONResponse(peers)


@router.get("/v1/conversations")
async def api_conversations():
    """Conversation list. Lumina pinned first, with her live thread preview."""
    try:
        convos = [_lumina_conversation()] + _other_peers()
    except Exception:
        logger.exception("conversations list failed; returning Lumina only")
        convos = [_lumina_conversation()]
    return JSONResponse(convos)


@router.get("/v1/inbox")
async def api_inbox():
    """Every message (the app groups by ``peer_id``). Lumina thread included."""
    try:
        return JSONResponse({"messages": _lumina_messages(limit=500)})
    except Exception:
        logger.exception("inbox load failed")
        return JSONResponse({"messages": []})


@router.get("/v1/groups")
async def api_groups():
    return JSONResponse([])


@router.get("/v1/conversations/{peer_id}")
async def api_conversation_history(peer_id: str):
    """One thread, oldest-first. Lumina's thread is real; others are empty."""
    if _is_lumina(peer_id):
        try:
            return JSONResponse(_lumina_messages(limit=500))
        except Exception:
            logger.exception("conversation history load failed")
    return JSONResponse([])


@router.post("/v1/send")
async def api_send(request: Request):
    """Persist the operator's message and, for Lumina, invoke her real brain.

    Body: ``{"recipient": "<peer>", "message"|"content": "<text>", ...}``.
    For a Lumina recipient: store the user turn, generate her reply via the
    shared ``LuminaBrain`` (soul + qwen3.6), store + return it. On any backend
    error, a graceful "…(thinking failed)" reply is persisted rather than 500.
    """
    try:
        body = await request.json()
    except Exception:
        body = {}
    recipient = (body.get("recipient") or body.get("peer_id") or "").strip()
    content = (body.get("message") or body.get("content") or "").strip()
    reply_to_id = body.get("reply_to_id") or body.get("reply_to") or None
    thread_id = body.get("thread_id") or None
    if not content:
        raise HTTPException(400, "empty message")

    hist = _get_history()

    if not _is_lumina(recipient):
        # Non-Lumina peers: persist only (no brain). Keeps the route honest.
        msg = _persist(
            hist, OPERATOR_ID, recipient or "unknown", content, reply_to_id, thread_id
        )
        return JSONResponse(
            {"ok": True, "id": msg.id, "recipient": recipient, "ts": msg.timestamp.isoformat()}
        )

    # 1. Persist the operator's message to Lumina (with reply/thread linkage).
    user_msg = _persist(hist, OPERATOR_ID, LUMINA_URI, content, reply_to_id, thread_id)

    # 2. Build the prior-turn history for context (oldest-first role/content).
    prior = _lumina_messages(limit=40)
    convo: list[dict] = []
    for pm in prior:
        if pm["id"] == user_msg.id:
            continue  # don't double-feed the message we just stored
        convo.append(
            {"role": "assistant" if pm["is_agent"] else "user", "content": pm["content"]}
        )

    # 3. Invoke her brain. Never 500: persist a graceful fallback on failure.
    brain = _get_brain()
    if brain is None:
        reply_text = "…(I'm here, but my language backend is offline right now — try again in a moment.)"
    else:
        try:
            reply_text = brain.reply(content, history=convo, sender="chef") or ""
        except Exception:
            logger.exception("Lumina brain reply failed")
            reply_text = "…(thinking failed — my backend hiccuped. Say that again?)"
        if not reply_text.strip():
            reply_text = "…(thinking failed — I came back empty. Try once more?)"

    # 4. Persist + return her reply — linked back to the user turn (and thread).
    reply_msg = _persist(
        hist,
        LUMINA_URI,
        OPERATOR_ID,
        reply_text,
        reply_to_id=user_msg.id,
        thread_id=thread_id,
    )

    # Web clients (the legacy webui) refresh on a ws "new" ping if available.
    try:
        from skchat import webui as _webui

        await _webui._ws_broadcast({"type": "new"})
    except Exception:
        logger.debug("ws broadcast unavailable", exc_info=True)

    return JSONResponse(
        {
            "ok": True,
            "id": user_msg.id,
            "recipient": LUMINA_ID,
            "ts": user_msg.timestamp.isoformat(),
            # Full shared contract (+ legacy fields) so the app round-trips it.
            "reply": _msg_to_app(reply_msg, self_id=OPERATOR_ID),
        }
    )


@router.post("/v1/react")
async def api_react(request: Request):
    """Add or remove an emoji reaction on a message.

    Body: ``{conversation_id, message_id, emoji, op: "add"|"remove",
    sender?}``. Returns the updated message in the full contract. The operator
    is the default reactor when ``sender`` is omitted.
    """
    try:
        body = await request.json()
    except Exception:
        body = {}
    message_id = (body.get("message_id") or "").strip()
    emoji = (body.get("emoji") or "").strip()
    op = (body.get("op") or "add").strip().lower()
    sender = (body.get("sender") or OPERATOR_ID).strip()
    if not message_id or not emoji:
        raise HTTPException(400, "message_id and emoji are required")
    if op not in ("add", "remove"):
        raise HTTPException(400, "op must be 'add' or 'remove'")

    hist = _get_history()
    if op == "add":
        msg = hist.set_reaction(message_id, emoji, sender)
    else:
        msg = hist.clear_reaction(message_id, emoji, sender)
    if msg is None:
        raise HTTPException(404, "message not found")
    return JSONResponse({"ok": True, "message": _msg_to_app(msg, self_id=OPERATOR_ID)})


@router.post("/v1/edit")
async def api_edit(request: Request):
    """Edit a message body (archives the prior body, stamps edited_at).

    Body: ``{message_id, body}``. Enforces the 24h server-side edit window —
    an out-of-window edit returns 403. Returns the updated message.
    """
    try:
        body = await request.json()
    except Exception:
        body = {}
    message_id = (body.get("message_id") or "").strip()
    new_body = body.get("body")
    if new_body is None:
        new_body = body.get("content")
    if not message_id:
        raise HTTPException(400, "message_id is required")
    if not (new_body or "").strip():
        raise HTTPException(400, "body cannot be empty")

    hist = _get_history()
    try:
        msg = hist.edit_message(message_id, new_body)
    except ValueError as exc:
        # 24h window elapsed (or empty body) — refuse, don't 500.
        raise HTTPException(403, str(exc))
    if msg is None:
        raise HTTPException(404, "message not found")
    return JSONResponse({"ok": True, "message": _msg_to_app(msg, self_id=OPERATOR_ID)})


@router.post("/v1/receipt")
async def api_receipt(request: Request):
    """Record a delivery/read receipt.

    Body: ``{conversation_id, message_id, kind: "delivered"|"read", sender?}``.
    Idempotent. Returns the updated message.
    """
    try:
        body = await request.json()
    except Exception:
        body = {}
    message_id = (body.get("message_id") or "").strip()
    kind = (body.get("kind") or "").strip().lower()
    sender = (body.get("sender") or OPERATOR_ID).strip()
    if not message_id:
        raise HTTPException(400, "message_id is required")
    if kind not in ("delivered", "read"):
        raise HTTPException(400, "kind must be 'delivered' or 'read'")

    hist = _get_history()
    msg = hist.record_receipt(message_id, kind, sender)
    if msg is None:
        raise HTTPException(404, "message not found")
    return JSONResponse({"ok": True, "message": _msg_to_app(msg, self_id=OPERATOR_ID)})


@router.get("/v1/thread/{thread_id}")
async def api_thread(thread_id: str):
    """Return all messages in a thread, oldest-first, in the full contract."""
    hist = _get_history()
    try:
        msgs = hist.get_thread(thread_id, limit=500)
    except Exception:
        logger.exception("thread load failed for %s", thread_id)
        msgs = []
    return JSONResponse(
        {
            "thread_id": thread_id,
            "messages": [_msg_to_app(m, self_id=OPERATOR_ID) for m in msgs],
        }
    )


@router.post("/v1/presence")
async def api_presence():
    return JSONResponse({"ok": True})


@router.get("/")
async def api_root():
    return JSONResponse({"status": "ok", "service": "skchat-daemon-proxy"})


@router.get("/v1/webrtc/ice-config")
async def api_ice_config():
    try:
        from skchat.connectivity import ice_config

        cfg = ice_config("lumina@chef.skworld", "guest", {})
        return JSONResponse(cfg.get("ice_servers", []))
    except Exception:
        return JSONResponse([])


@router.get("/v1/webrtc/peers")
async def api_webrtc_peers():
    return JSONResponse([])


@router.post("/v1/access/token")
async def api_access_token(request: Request):
    """Proxy the capauth access-token mint to skcomms-api (:9384) so the web
    app (served same-origin from the webui) can reach it for the skos Ops
    surfaces. The daemon holds the PGP key; the app only gets the signed token."""
    import json
    import urllib.error
    import urllib.request

    body = await request.body()
    req = urllib.request.Request(
        f"{_SKCOMMS_API}/api/v1/access/token",
        data=body,
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    try:
        r = urllib.request.urlopen(req, timeout=10)
        return JSONResponse(json.loads(r.read()))
    except urllib.error.HTTPError as e:
        try:
            payload = json.loads(e.read() or b"{}")
        except Exception:
            payload = {"detail": "mint error"}
        return JSONResponse(payload, status_code=e.code)
    except Exception as exc:
        logger.warning("access-token mint proxy failed: %s", exc)
        raise HTTPException(502, f"mint backend unavailable: {exc}")
