"""Daemon API proxy — serves the endpoints the Flutter app needs by stitching
together skchat daemon, skcapstone API, and webui behind a single /api/* prefix.

Chat surface (the part the Flutter app's chat UI reads):
  * GET  /api/v1/peers          — contacts; **Lumina is always present + first**
  * GET  /api/v1/conversations  — conversation list; Lumina pinned online
  * GET  /api/v1/inbox          — every message (app groups by peer_id)
  * GET  /api/v1/conversations/{peer_id} — one thread, oldest-first
  * POST /api/v1/send           — persists the message and, for Lumina, invokes
                                   her real brain (soul + qwen3.6) and returns
                                   + persists her reply.

History is backed by the real ``skchat.history.ChatHistory`` (JSONL/SQLite) so
the Lumina thread survives reloads. Lumina's reply is generated by the SAME
``LuminaBrain`` the Telegram bridge drives (``scripts/bridge_consciousness``) —
the genuine ``lumina-unhinged`` soul + FEB on qwen3.6, not a generic assistant.
"""

from __future__ import annotations

import logging
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import JSONResponse

logger = logging.getLogger("skchat.daemon_proxy")

router = APIRouter(prefix="/api")

# Where the capauth access-token mint + the access plane live (skcomms-api).
_SKCOMMS_API = "http://127.0.0.1:9384"

# ── Lumina identity (the always-present companion) ─────────────────────────── #
LUMINA_ID = "lumina@chef.skworld"
LUMINA_URI = "capauth:lumina@skworld.io"
LUMINA_NAME = "Lumina"
LUMINA_FINGERPRINT = "02BC0EB3CAD31DB691A753C70C5629AB893F9746"
# The local operator's identity for messages they send in-app.
OPERATOR_ID = "chef@skworld.io"

# The webui process runs as the agent (SKAGENT=lumina). Self-identity used as
# the "sender" when persisting Lumina's replies.
_AGENT_HOME = os.environ.get(
    "SKC_BRIDGE_AGENT_HOME", os.path.expanduser("~/.skcapstone/agents/lumina")
)


def _proxy(url: str) -> dict | list:
    import json
    import urllib.request

    try:
        r = urllib.request.urlopen(url, timeout=5)
        return json.loads(r.read())
    except Exception as exc:
        logger.debug("daemon_proxy: %s failed: %s", url, exc)
        raise HTTPException(502, f"backend unavailable: {exc}")


# --------------------------------------------------------------------------- #
# History + brain (lazy singletons)
# --------------------------------------------------------------------------- #
_HISTORY = None
_BRAIN = None


def _get_history():
    """Return the shared ``ChatHistory`` (JSONL/SQLite), created on first use."""
    global _HISTORY
    if _HISTORY is None:
        from skchat.history import ChatHistory

        _HISTORY = ChatHistory()
    return _HISTORY


def _get_brain():
    """Return the shared ``LuminaBrain`` (soul + qwen3.6), created on first use.

    Imports the SAME module the Telegram bridge uses (``bridge_consciousness``
    in ``scripts/``) so the app drives the identical brain — reused, not rebuilt.
    Returns ``None`` if the brain can't be constructed (degrades gracefully).
    """
    global _BRAIN
    if _BRAIN is not None:
        return _BRAIN
    try:
        scripts_dir = str(Path(__file__).resolve().parents[2] / "scripts")
        if scripts_dir not in sys.path:
            sys.path.insert(0, scripts_dir)
        from bridge_consciousness import LuminaBrain  # type: ignore

        _BRAIN = LuminaBrain(home=_AGENT_HOME, agent=LUMINA_NAME)
    except Exception:
        logger.exception("LuminaBrain unavailable — Lumina will use a fallback reply")
        _BRAIN = None
    return _BRAIN


def _persist(
    hist,
    sender: str,
    recipient: str,
    content: str,
    reply_to_id=None,
    thread_id=None,
    content_type: str | None = None,
    rich: dict | None = None,
):
    """Build a ChatMessage (with optional reply/thread linkage) and save it.

    ``ChatHistory.add_message`` only takes scalars, so we construct the model
    directly to carry reply_to_id/thread_id (and the optional typed-message
    ``content_type``/``rich`` payload — P1 contract), then ``save`` it.
    """
    from skchat.models import ChatMessage

    fields: dict = {
        "sender": sender,
        "recipient": recipient,
        "content": content,
        "reply_to_id": reply_to_id or None,
        "thread_id": thread_id or None,
    }
    if content_type:
        fields["content_type"] = content_type
    if rich is not None:
        fields["rich"] = rich
    msg = ChatMessage(**fields)
    hist.save(msg)
    return msg


def _is_lumina(peer: str) -> bool:
    """True if *peer* addresses Lumina (any of her known aliases)."""
    if not peer:
        return False
    p = peer.strip().lower()
    return p in {
        "lumina",
        LUMINA_ID.lower(),
        LUMINA_URI.lower(),
        "lumina@skworld.io",
        LUMINA_FINGERPRINT.lower(),
    }


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def _operator_online() -> bool:
    """Lumina shows online whenever the operator is using the app.

    This request itself proves the operator is present, so for the single-
    operator sovereign deployment Lumina is online whenever the app is open.
    """
    return True


# --------------------------------------------------------------------------- #
# Message shaping (Flutter contract)
# --------------------------------------------------------------------------- #
def _iso(ts) -> str | None:
    if ts is None:
        return None
    return ts.isoformat() if hasattr(ts, "isoformat") else str(ts)


def _msg_to_app(m, *, self_id: str) -> dict:
    """Map a stored ``ChatMessage`` to the app's message JSON.

    Emits the **full shared message contract** the Flutter half builds to:
    id, conversation_id, sender, content_type (short wire form), body, rich, ts,
    reply_to_id, thread_id, edited_at, edit_history, reactions, receipts —
    plus the legacy app fields (peer_id, content, timestamp, is_outbound,
    is_agent, sender_name, delivery_status, is_encrypted) so the existing
    webui/app keep working. ``body`` is ALWAYS present (Golden rule): even an
    unknown ``content_type`` carries a human-readable fallback.
    """
    from skchat.models import ContentType

    sender = getattr(m, "sender", "") or ""
    recipient = getattr(m, "recipient", "") or ""
    outbound = not _is_lumina(sender) and _is_lumina(recipient)
    # The peer of the conversation = whichever party is Lumina.
    peer = LUMINA_ID if (_is_lumina(sender) or _is_lumina(recipient)) else recipient
    ts_iso = _iso(getattr(m, "timestamp", None)) or _now_iso()
    is_agent = _is_lumina(sender)
    body = getattr(m, "content", "") or ""

    # reactions → {emoji: [sender, ...]} (or None if none)
    reactions_map = None
    if hasattr(m, "reactions_map"):
        rm = m.reactions_map()
        reactions_map = rm or None

    # receipts → {delivered:[...], read:[...]} (or None)
    receipts = None
    rcpt = getattr(m, "receipts", None)
    if rcpt is not None:
        receipts = {"delivered": list(rcpt.delivered), "read": list(rcpt.read)}

    # edit_history → [{body, ts}] (or None)
    edit_history = None
    eh = getattr(m, "edit_history", None)
    if eh:
        edit_history = [{"body": e.body, "ts": _iso(e.ts)} for e in eh]

    return {
        # --- shared message contract (Flutter builds to this exact shape) ---
        "id": getattr(m, "id", ""),
        "conversation_id": peer,
        "sender": sender,
        "content_type": ContentType.to_wire(getattr(m, "content_type", "markdown")),
        "body": body,
        "rich": getattr(m, "rich", None),
        "ts": ts_iso,
        "reply_to_id": getattr(m, "reply_to_id", None),
        "thread_id": getattr(m, "thread_id", None),
        "edited_at": _iso(getattr(m, "edited_at", None)),
        "edit_history": edit_history,
        "reactions": reactions_map,
        "receipts": receipts,
        # --- legacy app fields (kept for back-compat) ---
        "peer_id": peer,
        "content": body,
        "timestamp": ts_iso,
        "is_outbound": outbound,
        "delivery_status": "sent",
        "is_encrypted": False,
        "is_agent": is_agent,
        "sender_name": LUMINA_NAME if is_agent else "You",
    }


def _group_msg_to_app(m, *, group_id: str) -> dict:
    """Map a stored group ``ChatMessage`` to the app's message JSON.

    Same shared contract as ``_msg_to_app`` but the ``conversation_id`` is the
    group id and directionality is "outbound iff the operator authored it".
    ``sender_name`` is the member's short handle (so the bubble shows who spoke);
    ``is_agent`` flags agent senders so the UI renders their soul colour.
    """
    from skchat.models import ContentType

    sender = getattr(m, "sender", "") or ""
    ts_iso = _iso(getattr(m, "timestamp", None)) or _now_iso()
    body = getattr(m, "content", "") or ""
    outbound = sender in (OPERATOR_ID, "chef", "chef@skworld.io")
    short = sender.split(":")[-1].split("@")[0]
    is_agent = _participant_is_agent(sender)

    reactions_map = None
    if hasattr(m, "reactions_map"):
        reactions_map = m.reactions_map() or None
    receipts = None
    rcpt = getattr(m, "receipts", None)
    if rcpt is not None:
        receipts = {"delivered": list(rcpt.delivered), "read": list(rcpt.read)}
    edit_history = None
    eh = getattr(m, "edit_history", None)
    if eh:
        edit_history = [{"body": e.body, "ts": _iso(e.ts)} for e in eh]

    return {
        "id": getattr(m, "id", ""),
        "conversation_id": group_id,
        "sender": sender,
        "content_type": ContentType.to_wire(getattr(m, "content_type", "markdown")),
        "body": body,
        "rich": getattr(m, "rich", None),
        "ts": ts_iso,
        "reply_to_id": getattr(m, "reply_to_id", None),
        "thread_id": getattr(m, "thread_id", None) or group_id,
        "edited_at": _iso(getattr(m, "edited_at", None)),
        "edit_history": edit_history,
        "reactions": reactions_map,
        "receipts": receipts,
        # legacy fields
        "peer_id": group_id,
        "content": body,
        "timestamp": ts_iso,
        "is_outbound": outbound,
        "delivery_status": "sent",
        "is_encrypted": False,
        "is_agent": is_agent,
        "sender_name": "You" if outbound else (short.title() or short),
    }


def _participant_is_agent(uri: str) -> bool:
    short = (uri or "").split(":")[-1].split("@")[0].lower()
    return short in {
        "lumina", "jarvis", "opus", "ava", "ara", "artisan", "herald",
        "sentinel", "architect", "scholar", "steward", "coder",
    }


def _group_messages(group_id: str, limit: int = 500) -> list[dict]:
    """Load a group's thread (oldest-first) in the app message contract."""
    from skchat import daemon_proxy_groups as G

    hist = _get_history()
    rows = G.group_thread_messages(hist, group_id, limit=limit)
    rows.sort(key=lambda x: getattr(x, "timestamp", _now_iso()))
    return [_group_msg_to_app(m, group_id=group_id) for m in rows]


def _is_group_message(m) -> bool:
    """True only if *m* genuinely belongs to a GROUP thread, not a 1:1 DM.

    A group's per-member fan-out copy is addressed to Lumina
    (recipient=capauth:lumina) but belongs to the GROUP thread — those must
    stay out of the 1:1 Lumina DM. A plain 1:1 DM can also carry a
    client-supplied ``thread_id`` (POST /api/v1/send accepts one for
    threaded replies within the direct chat) — that is NOT a group message
    and must be kept, so ``thread_id`` alone is never sufficient evidence.
    """
    from skchat import daemon_proxy_groups as G

    meta = getattr(m, "metadata", None) or {}
    r, s = str(getattr(m, "recipient", "")), str(getattr(m, "sender", ""))
    if meta.get("group_id"):
        return True
    if r.startswith("group:") or s.startswith("group:"):
        return True
    thread_id = getattr(m, "thread_id", None)
    if thread_id and G.load_group(thread_id) is not None:
        # thread_id happens to match a real, persisted group id.
        return True
    return False


def _lumina_messages(limit: int = 200) -> list[dict]:
    """Load the operator↔Lumina thread, oldest-first, in app message shape."""
    hist = _get_history()
    rows = hist.load(peer=LUMINA_URI, limit=limit)
    rows += hist.load(peer=LUMINA_ID, limit=limit)
    rows += hist.load(peer="lumina", limit=limit)
    # Dedup by id, keep only operator↔Lumina, sort oldest-first.
    seen: set[str] = set()
    msgs: list = []
    for m in rows:
        mid = getattr(m, "id", None)
        if mid in seen:
            continue
        seen.add(mid)
        s, r = getattr(m, "sender", ""), getattr(m, "recipient", "")
        if not (_is_lumina(s) or _is_lumina(r)):
            continue
        # Exclude GROUP messages only (see _is_group_message) — a genuine
        # 1:1 DM that happens to carry a client-supplied thread_id must be
        # kept, not dropped.
        if _is_group_message(m):
            continue
        msgs.append(m)
    msgs.sort(key=lambda x: getattr(x, "timestamp", _now_iso()))
    return [_msg_to_app(m, self_id=OPERATOR_ID) for m in msgs]


def _lumina_conversation() -> dict:
    """The pinned Lumina conversation entry (app conversation shape)."""
    msgs = _lumina_messages(limit=50)
    last = msgs[-1] if msgs else None
    return {
        "peer_id": LUMINA_ID,
        "display_name": LUMINA_NAME,
        "last_message": (last or {}).get("content", "") if last else "",
        "last_message_time": (last or {}).get("timestamp", _now_iso()),
        "soul_fingerprint": LUMINA_FINGERPRINT,
        "is_online": _operator_online(),
        "is_agent": True,
        "unread_count": 0,
        "last_delivery_status": "sent",
        "is_group": False,
        "member_count": 0,
        "avatar_url": "",
    }


def _other_peers() -> list[dict]:
    """Best-effort: known peers from ~/.skcapstone/peers/*.json (Lumina excluded).

    Lumina is added separately and pinned first; this just enriches the list.
    """
    import json

    out: list[dict] = []
    peers_dir = Path(os.path.expanduser("~/.skcapstone/peers"))
    if not peers_dir.is_dir():
        return out
    for p in sorted(peers_dir.glob("*.json")):
        try:
            data = json.loads(p.read_text())
        except Exception:
            continue
        handle = (data.get("handle") or data.get("identity") or p.stem).strip()
        if _is_lumina(handle) or _is_lumina(data.get("identity", "")) or p.stem == "lumina":
            continue
        out.append(
            {
                "peer_id": data.get("handle") or data.get("identity") or p.stem,
                "display_name": data.get("name") or p.stem.title(),
                "last_message": "",
                "last_message_time": _now_iso(),
                "soul_fingerprint": data.get("fingerprint", ""),
                "is_online": False,
                "is_agent": (data.get("agent_type") == "ai")
                or (data.get("entity_type") == "ai-agent"),
                "unread_count": 0,
                "last_delivery_status": "sent",
                "is_group": False,
                "member_count": 0,
                "avatar_url": "",
            }
        )
    return out


# --------------------------------------------------------------------------- #
# Misc passthrough routes (unchanged)
# --------------------------------------------------------------------------- #
@router.get("/health")
async def api_health():
    return _proxy("http://127.0.0.1:9385/health")


# --------------------------------------------------------------------------- #
# PQC Q5 — hybrid-KEM prekey store + endpoints
#
# The app publishes its device prekey (POST /api/v1/prekey); peers fetch each
# other's bundle (GET /api/v1/prekey/{peer}). Lumina publishes her OWN hybrid
# prekey too, so chef-app <-> lumina goes hybrid post-quantum. The send path
# (api_send) uses these to open inbound hybrid DMs + seal Lumina's replies.
# --------------------------------------------------------------------------- #


def _short_name(uri: str) -> str:
    s = uri[len("capauth:"):] if uri.startswith("capauth:") else uri
    return s.split("@")[0]


def _open_hybrid_inbound(token: str, *, sender_short: str) -> str | None:
    """Open a `pqdm1:` token addressed to Lumina. Returns plaintext or None."""
    try:
        from skchat import pq_prekeys as PQ
        from skcomms.pqdm import open_sealed
        import base64 as _b64

        priv = PQ.lumina_private()
        if priv is None:
            return None
        rest = token[len("pqdm1:"):]
        suite, _, b64 = rest.partition(":")
        sealed = _b64.b64decode(b64)
        clear = open_sealed(
            sealed, priv,
            sender=sender_short, recipient="lumina", expected_suite=suite,
        )
        return clear.decode("utf-8")
    except Exception:
        logger.debug("hybrid inbound open failed", exc_info=True)
        return None


def _seal_hybrid_outbound(plaintext: str, *, recipient_short: str) -> str | None:
    """Seal `plaintext` to the operator's stored prekey. Returns a `pqdm1:`
    token or None (no prekey / no backend → caller keeps the plaintext)."""
    try:
        from skchat import pq_prekeys as PQ
        from skcomms.pqdm import HYBRID_SUITE, PrekeyBundle, seal
        import base64 as _b64

        peer = PQ.load_peer_bundle(recipient_short)
        if not peer:
            return None
        bundle = PrekeyBundle.from_dict(peer)
        if not bundle.is_hybrid:
            return None
        sealed = seal(
            plaintext.encode("utf-8"), bundle,
            sender="lumina", recipient=recipient_short,
        )
        return f"pqdm1:{HYBRID_SUITE}:" + _b64.b64encode(sealed).decode("ascii")
    except Exception:
        logger.debug("hybrid outbound seal failed", exc_info=True)
        return None


@router.post("/v1/prekey")
async def api_publish_prekey(request: Request):
    """Publish a peer's (the app's) hybrid-KEM prekey bundle.

    Body = a ``PrekeyBundle`` dict: ``{suite, hybrid_public_hex, signature?,
    key_id?, device_id?}``. Stored keyed by the operator short name (``chef``)
    unless an explicit ``owner`` is given. Returns ``{ok, stored, hybrid}``.
    """
    from skchat import pq_prekeys as PQ

    try:
        body = await request.json()
    except Exception:
        body = {}
    if not isinstance(body, dict):
        raise HTTPException(400, "prekey bundle must be an object")
    owner = _short_name((body.get("owner") or OPERATOR_ID))
    PQ.store_peer_bundle(owner, body)
    return JSONResponse(
        {"ok": True, "stored": owner, "hybrid": PQ.peer_is_hybrid(owner)}
    )


@router.get("/v1/prekey/{peer:path}")
async def api_get_prekey(peer: str):
    """Fetch a peer's prekey bundle. ``lumina`` returns Lumina's OWN hybrid
    prekey (generated on demand); any other peer returns its published bundle,
    or a classical (non-hybrid) bundle if none was published."""
    from skchat import pq_prekeys as PQ

    short = _short_name(peer)
    if short == "lumina":
        return JSONResponse({"prekey": PQ.lumina_bundle()})
    stored = PQ.load_peer_bundle(short)
    if stored is None:
        return JSONResponse({"prekey": {"suite": PQ.CLASSICAL_SUITE, "hybrid_public_hex": ""}})
    return JSONResponse({"prekey": stored})


@router.get("/v1/status")
async def api_status():
    return _proxy("http://127.0.0.1:9383/api/v1/household/agents")


@router.get("/board")
async def api_board():
    """Same-origin proxy to the skcapstone dashboard (:7778) so the coord/Team
    Board works over any origin (tailscale URL / funnel) — :7778 isn't exposed
    through tailscale serve, only the webui is."""
    return _proxy("http://127.0.0.1:7778/api/board")


@router.get("/v1/capabilities")
async def api_capabilities():
    """Same-origin proxy to the skcomms-api capability/service-discovery doc."""
    return _proxy(f"{_SKCOMMS_API}/api/v1/capabilities")


@router.get("/v1/household/agents")
async def api_agents():
    return _proxy("http://127.0.0.1:9383/api/v1/household/agents")


@router.get("/v1/identity")
async def api_identity():
    return JSONResponse(
        {"identity": LUMINA_ID, "display_name": LUMINA_NAME, "fingerprint": "active"}
    )


# --------------------------------------------------------------------------- #
# Chat surface — Lumina always present + real history + real replies
# --------------------------------------------------------------------------- #
@router.get("/v1/peers")
async def api_peers():
    """Contacts. Lumina is ALWAYS first; other known peers follow."""
    try:
        peers = [_lumina_conversation()] + _other_peers()
    except Exception:
        logger.exception("peers list failed; returning Lumina only")
        peers = [_lumina_conversation()]
    return JSONResponse(peers)


@router.get("/v1/conversations")
async def api_conversations():
    """Conversation list. Lumina pinned first, then peers, then GROUPS.

    Groups carry ``is_group:true`` + ``member_count`` so the Flutter
    ``GroupsNotifier`` (filters on ``is_group``) and ``chatsProvider`` (unified
    list) both pick them up from this one endpoint.
    """
    try:
        convos = [_lumina_conversation()] + _other_peers() + _group_conversations()
    except Exception:
        logger.exception("conversations list failed; returning Lumina only")
        convos = [_lumina_conversation()]
    return JSONResponse(convos)


def _group_conversations() -> list[dict]:
    """All persisted groups in the app conversation shape (``is_group:true``)."""
    from skchat import daemon_proxy_groups as G

    out: list[dict] = []
    try:
        for grp in G.list_groups():
            out.append(G.group_to_conversation(grp))
    except Exception:
        logger.exception("group conversation list failed")
    return out


@router.get("/v1/inbox")
async def api_inbox():
    """Every message (the app groups by ``peer_id``). Lumina thread included."""
    try:
        return JSONResponse({"messages": _lumina_messages(limit=500)})
    except Exception:
        logger.exception("inbox load failed")
        return JSONResponse({"messages": []})


@router.post("/v1/inbox")
async def api_inbox_federation_proxy(request: Request):
    """Federation S2S inbox — proxied to skcomms-api.

    ``/api/v1/inbox`` is overloaded: the app GETs it (thread list, above) while
    remote peers POST signed envelopes to it for delivery. When this webui is
    the single 443 front door for ``/api/v1/*``, the app's GET must land here
    (daemon_proxy) — but a POST must still reach the federation receiver
    (skcomms-api, :9384) or agents stop receiving messages. Proxy the POST body
    through verbatim so both work on one path.
    """
    import httpx
    from fastapi import Response

    body = await request.body()
    # Forward the request VERBATIM — all headers (signatures/auth live here) and
    # query params — so the federation receiver sees exactly what the app sent.
    # Only drop hop-by-hop headers that httpx must set itself.
    _skip = {"host", "content-length", "connection", "transfer-encoding"}
    fwd_headers = {k: v for k, v in request.headers.items() if k.lower() not in _skip}
    try:
        async with httpx.AsyncClient() as client:
            r = await client.post(
                "http://localhost:9384/api/v1/inbox",
                content=body,
                headers=fwd_headers,
                params=dict(request.query_params),
                timeout=20.0,
            )
        resp_headers = {
            k: v for k, v in r.headers.items()
            if k.lower() not in ("content-length", "transfer-encoding", "connection")
        }
        return Response(content=r.content, status_code=r.status_code, headers=resp_headers)
    except Exception as exc:  # noqa: BLE001
        logger.warning("federation inbox proxy -> :9384 failed: %s", exc)
        raise HTTPException(502, "federation inbox unreachable")


@router.get("/v1/groups")
async def api_groups():
    """List all groups (app conversation shape, ``is_group:true``)."""
    return JSONResponse(_group_conversations())


@router.post("/v1/groups")
async def api_create_group(request: Request):
    """Create a group. Body: ``{name, members?[], description?, acl?}``.

    ``members`` is a list of ``{identity}`` (the Flutter client shape) or bare
    handle strings. The creator (operator) is added as admin automatically.
    Returns the ``CreateGroupResult`` contract.
    """
    from skchat import daemon_proxy_groups as G

    try:
        body = await request.json()
    except Exception:
        body = {}
    name = (body.get("name") or "").strip()
    if not name:
        raise HTTPException(400, "name is required")
    description = body.get("description") or ""
    acl = body.get("acl") or None
    raw_members = body.get("members") or []
    members: list[str] = []
    for m in raw_members:
        if isinstance(m, dict):
            ident = m.get("identity") or m.get("identity_uri") or ""
        else:
            ident = str(m)
        if ident:
            members.append(ident)

    group = G.create_group(
        name=name,
        creator_uri=OPERATOR_ID,
        members=members,
        description=description,
        acl=acl,
    )
    return JSONResponse(G.create_result(group))


@router.put("/v1/groups/{group_id}")
async def api_update_group(group_id: str, request: Request):
    """Update group name/description/acl. Body: ``{name?, description?, acl?}``."""
    from skchat import daemon_proxy_groups as G

    group = G.load_group(group_id)
    if group is None:
        raise HTTPException(404, "group not found")
    try:
        body = await request.json()
    except Exception:
        body = {}
    G.update_group(
        group,
        name=body.get("name"),
        description=body.get("description"),
        acl=body.get("acl"),
    )
    return JSONResponse({"ok": True, "group": G.group_to_conversation(group)})


@router.delete("/v1/groups/{group_id}")
async def api_delete_group(group_id: str):
    """Delete a group entirely (admin-only). Removes the store file + tombstones.

    Admin gate: only an admin of the group (the creator/operator) may delete it.
    Non-admins get 403 — the app shows them "Leave group" instead. A missing
    group is 404. On success the group file is removed and a ``<id>.deleted.json``
    tombstone is written so it doesn't get resurrected by a re-list / re-sync.
    """
    from skchat import daemon_proxy_groups as G

    group = G.load_group(group_id)
    if group is None:
        raise HTTPException(404, "group not found")
    if not G.is_admin(group, OPERATOR_ID):
        raise HTTPException(403, "only an admin can delete this group")
    G.delete_group(group_id)
    return JSONResponse({"ok": True, "deleted": group_id})


@router.get("/v1/groups/{group_id}/members")
async def api_group_members(group_id: str):
    """List a group's members in the app member shape."""
    from skchat import daemon_proxy_groups as G

    group = G.load_group(group_id)
    if group is None:
        raise HTTPException(404, "group not found")
    return JSONResponse([G.member_to_app(m) for m in group.members])


@router.post("/v1/groups/{group_id}/members")
async def api_group_add_member(group_id: str, request: Request):
    """Add (or re-role) a member. Body: ``{identity, role?}``.

    If the id refers to a 1:1 conversation that is not yet a group, this
    PROMOTES it to a group of the same id (carrying the existing history).
    """
    from skchat import daemon_proxy_groups as G

    try:
        body = await request.json()
    except Exception:
        body = {}
    identity = (body.get("identity") or body.get("identity_uri") or "").strip()
    role = (body.get("role") or "member").strip()
    if not identity:
        raise HTTPException(400, "identity is required")

    group = G.load_group(group_id)
    if group is None:
        # Promote a 1:1 (or create a fresh group keyed by this id).
        hist = _get_history()
        group = G.promote_one_to_one(
            hist, peer_id=group_id, new_member=identity, operator_uri=OPERATOR_ID
        )
        return JSONResponse(
            {"ok": True, "promoted": True, "group": G.group_to_conversation(group),
             "members": [G.member_to_app(m) for m in group.members]}
        )

    if not G.can_add_members(group, OPERATOR_ID):
        raise HTTPException(403, "not allowed to add members")
    added = G.add_member(group, identity, role=role)
    return JSONResponse(
        {"ok": True, "added": added,
         "members": [G.member_to_app(m) for m in group.members]}
    )


@router.delete("/v1/groups/{group_id}/members/self")
async def api_group_leave(group_id: str):
    """Leave a group (remove the operator). Rotates the group key."""
    from skchat import daemon_proxy_groups as G

    group = G.load_group(group_id)
    if group is None:
        raise HTTPException(404, "group not found")
    G.remove_member(group, OPERATOR_ID)
    return JSONResponse({"ok": True, "left": group_id})


@router.delete("/v1/groups/{group_id}/members/{identity:path}")
async def api_group_remove_member(group_id: str, identity: str):
    """Remove a member from a group. Rotates the group key (forward secrecy)."""
    from skchat import daemon_proxy_groups as G

    group = G.load_group(group_id)
    if group is None:
        raise HTTPException(404, "group not found")
    if not G.can_add_members(group, OPERATOR_ID):
        raise HTTPException(403, "not allowed to remove members")
    removed = G.remove_member(group, identity)
    if not removed:
        raise HTTPException(404, "member not found")
    return JSONResponse(
        {"ok": True, "removed": identity,
         "members": [G.member_to_app(m) for m in group.members]}
    )


# --------------------------------------------------------------------------- #
# Group A/V calls (Phase 3 — on-the-fly group video + screenshare)
# --------------------------------------------------------------------------- #
def _group_caller_uri(group) -> str:
    """Return the operator's membership URI in *group* (the call caller).

    The app runs as the local operator. The operator joins groups as
    ``OPERATOR_ID`` (``create_group(creator_uri=OPERATOR_ID)``); if a different
    membership form was stored we fall back to ``OPERATOR_ID`` so the membership
    gate is evaluated against the real roster.
    """
    if group is not None and group.get_member(OPERATOR_ID) is not None:
        return OPERATOR_ID
    return OPERATOR_ID


def _group_call_sfu_url(request: Request) -> str:
    """The SFU wss URL appropriate for the requesting client (public-aware)."""
    try:
        from skchat.livekit_routes import public_aware_livekit_url

        return public_aware_livekit_url(request)
    except Exception:
        import os as _os

        return _os.getenv("SKCHAT_LIVEKIT_URL", "ws://skworld-100:7880")


@router.post("/v1/groups/{group_id}/call/start")
async def api_group_call_start(group_id: str, request: Request):
    """Start (or join) a group A/V call: mint a member-scoped token + ring.

    Body (all optional): ``{topic?, ring?:bool}``. ``ring`` defaults to true —
    fans a signed CALL_INVITE out to every other member (reusing the 1:1 ring,
    surfaced at ``GET /call/incoming``). Returns the deterministic room, the
    caller's room-scoped token, the SFU url, and the member roster.

    Refuses (403) if the caller is not a member; 404 if the group is unknown;
    503 if LiveKit creds are not configured.
    """
    from skchat import daemon_proxy_groupcall as GC
    from skchat import daemon_proxy_groups as G
    from skchat.livekit_routes import _have_creds

    group = G.load_group(group_id)
    if group is None:
        raise HTTPException(404, "group not found")
    if not _have_creds():
        raise HTTPException(503, "livekit not configured")

    try:
        body = await request.json()
    except Exception:
        body = {}
    topic = (body.get("topic") or "").strip()
    do_ring = body.get("ring", True)

    caller = _group_caller_uri(group)
    sfu_url = _group_call_sfu_url(request)
    try:
        ctx = GC.group_call_context(group, caller, sfu_url)
    except PermissionError:
        raise HTTPException(403, "not a member of this group")
    except ImportError:
        raise HTTPException(503, "livekit-api not installed")

    rung: list[str] = []
    if do_ring:
        try:
            rung = GC.ring_members(group, caller, ctx["room"], sfu_url, topic=topic)
        except Exception:
            logger.exception("group ring failed (call still proceeds)")
    ctx["rung"] = rung
    return JSONResponse(ctx)


@router.post("/v1/groups/{group_id}/call/join")
async def api_group_call_join(group_id: str, request: Request):
    """Join an in-progress group call (mint a member-scoped token, no ring).

    Same membership gate as ``/call/start`` — a late-joiner gets a room-scoped
    token + the roster; the LiveKit room shows who is already present.
    """
    from skchat import daemon_proxy_groupcall as GC
    from skchat import daemon_proxy_groups as G
    from skchat.livekit_routes import _have_creds

    group = G.load_group(group_id)
    if group is None:
        raise HTTPException(404, "group not found")
    if not _have_creds():
        raise HTTPException(503, "livekit not configured")

    caller = _group_caller_uri(group)
    sfu_url = _group_call_sfu_url(request)
    try:
        ctx = GC.group_call_context(group, caller, sfu_url)
    except PermissionError:
        raise HTTPException(403, "not a member of this group")
    except ImportError:
        raise HTTPException(503, "livekit-api not installed")
    return JSONResponse(ctx)


@router.get("/v1/groups/{group_id}/call/participants")
async def api_group_call_participants(group_id: str):
    """List participants currently connected to the group's LiveKit room.

    Queries the SFU's RoomService (``ListParticipants``) for the deterministic
    room. Returns ``{room, active, participants:[{identity, ...}]}``. Degrades
    to an empty active-list (never 500) if the SFU/API is unreachable, so the UI
    can still show the membership roster as "who could join".
    """
    from skchat import daemon_proxy_groupcall as GC
    from skchat import daemon_proxy_groups as G

    group = G.load_group(group_id)
    if group is None:
        raise HTTPException(404, "group not found")
    room = GC.derive_group_room(group_id)
    participants = await _livekit_list_participants(room)
    return JSONResponse(
        {
            "room": room,
            "active": len(participants),
            "participants": participants,
            "members": [G.member_to_app(m) for m in group.members],
        }
    )


async def _livekit_list_participants(room: str) -> list[dict]:
    """Best-effort SFU participant list for *room* (empty list on any failure)."""
    import os as _os

    try:
        from livekit import api  # soft dep
    except ImportError:
        return []
    url = _os.getenv("SKCHAT_LIVEKIT_URL", "ws://skworld-100:7880")
    http_url = url.replace("ws://", "http://").replace("wss://", "https://")
    key = _os.getenv("SKCHAT_LIVEKIT_API_KEY", "")
    secret = _os.getenv("SKCHAT_LIVEKIT_API_SECRET", "")
    if not (key and secret):
        return []
    lk = api.LiveKitAPI(http_url, key, secret)
    try:
        resp = await lk.room.list_participants(api.ListParticipantsRequest(room=room))
        out = []
        for p in getattr(resp, "participants", []) or []:
            out.append(
                {
                    "identity": getattr(p, "identity", ""),
                    "name": getattr(p, "name", ""),
                    "state": str(getattr(p, "state", "")),
                    "is_publisher": bool(getattr(p, "tracks", None)),
                }
            )
        return out
    except Exception as exc:
        logger.debug("list_participants(%s) failed: %s", room, exc)
        return []
    finally:
        try:
            await lk.aclose()
        except Exception:
            pass


@router.get("/v1/conversations/{peer_id}")
async def api_conversation_history(peer_id: str):
    """One thread, oldest-first. Lumina's thread, GROUP threads, or empty.

    A group id resolves to its fanned-out group thread (same message contract
    as a 1:1) so opening a group reuses the standard conversation view.
    """
    if _is_lumina(peer_id):
        try:
            return JSONResponse(_lumina_messages(limit=500))
        except Exception:
            logger.exception("conversation history load failed")
        return JSONResponse([])

    # Group thread?
    try:
        from skchat import daemon_proxy_groups as G

        if G.load_group(peer_id) is not None:
            return JSONResponse(_group_messages(peer_id, limit=500))
    except Exception:
        logger.exception("group history load failed for %s", peer_id)
    return JSONResponse([])


@router.post("/v1/send")
async def api_send(request: Request):
    """Persist the operator's message and, for Lumina, invoke her real brain.

    Body: ``{"recipient": "<peer>", "message"|"content": "<text>", ...}``.
    For a Lumina recipient: store the user turn, generate her reply via the
    shared ``LuminaBrain`` (soul + qwen3.6), store + return it. On any backend
    error, a graceful "…(thinking failed)" reply is persisted rather than 500.
    """
    try:
        body = await request.json()
    except Exception:
        body = {}
    recipient = (body.get("recipient") or body.get("peer_id") or "").strip()
    content = (body.get("message") or body.get("content") or "").strip()
    reply_to_id = body.get("reply_to_id") or body.get("reply_to") or None
    thread_id = body.get("thread_id") or None
    group_id = (body.get("group_id") or "").strip()

    # Typed-message contract (P1): an optional content_type + rich payload.
    # The Golden rule holds — an unknown type still rides its `body`/content.
    content_type = (body.get("content_type") or "").strip() or None
    rich = body.get("rich")

    # Location typed message (Phase 4): server-side validate + coarse-by-default.
    # The body (fallback text) is *derived* from the validated payload so it
    # always matches the stored (possibly coarsened) coordinates.
    if content_type == "location":
        from skchat import location as _loc

        try:
            content, rich = _loc.shape_location_message(rich, content)
        except _loc.LocationError as exc:
            raise HTTPException(400, f"invalid location: {exc}")

    # PQC Q5: if the operator's app sent a hybrid-sealed `pqdm1:` token, open it
    # with Lumina's hybrid private key so the brain + history see plaintext. The
    # conversation is recorded hybrid so the reply is sealed back symmetrically.
    convo_is_hybrid = False
    if content.startswith("pqdm1:"):
        opened = _open_hybrid_inbound(content, sender_short="chef")
        if opened is not None:
            content = opened
            convo_is_hybrid = True

    if not content:
        raise HTTPException(400, "empty message")

    hist = _get_history()

    # Group send: fan out to members + persist on the group thread.
    target_group = group_id or recipient
    # Never treat an agent (Lumina) 1:1 as a group — a stray same-id group file
    # (e.g. from promoting her DM) must not hijack the brain-reply path.
    if target_group and not _is_lumina(recipient):
        try:
            from skchat import daemon_proxy_groups as G

            group = G.load_group(target_group)
        except Exception:
            group = None
        if group is not None:
            if not G.can_post(group, OPERATOR_ID):
                raise HTTPException(403, "this group is read-only (admins only)")
            msg = G.fan_out_send(
                group, hist, OPERATOR_ID, content,
                reply_to_id=reply_to_id, thread_id=group.id,
                content_type=content_type, rich=rich,
            )
            try:
                from skchat import webui as _webui

                await _webui._ws_broadcast({"type": "new"})
            except Exception:
                logger.debug("ws broadcast unavailable", exc_info=True)
            return JSONResponse(
                {
                    "ok": True,
                    "id": msg.id,
                    "recipient": group.id,
                    "group_id": group.id,
                    "ts": msg.timestamp.isoformat(),
                    "message": _group_msg_to_app(msg, group_id=group.id),
                }
            )

    if not _is_lumina(recipient):
        # Non-Lumina peers: persist only (no brain). Keeps the route honest.
        msg = _persist(
            hist, OPERATOR_ID, recipient or "unknown", content, reply_to_id, thread_id,
            content_type=content_type, rich=rich,
        )
        return JSONResponse(
            {
                "ok": True,
                "id": msg.id,
                "recipient": recipient,
                "ts": msg.timestamp.isoformat(),
                "message": _msg_to_app(msg, self_id=OPERATOR_ID),
            }
        )

    # 1. Persist the operator's message to Lumina (with reply/thread linkage).
    user_msg = _persist(
        hist, OPERATOR_ID, LUMINA_URI, content, reply_to_id, thread_id,
        content_type=content_type, rich=rich,
    )

    # 2. Build the prior-turn history for context (oldest-first role/content).
    prior = _lumina_messages(limit=40)
    convo: list[dict] = []
    for pm in prior:
        if pm["id"] == user_msg.id:
            continue  # don't double-feed the message we just stored
        convo.append(
            {"role": "assistant" if pm["is_agent"] else "user", "content": pm["content"]}
        )

    # 3. Invoke her brain. Never 500: persist a graceful fallback on failure.
    brain = _get_brain()
    if brain is None:
        reply_text = "…(I'm here, but my language backend is offline right now — try again in a moment.)"
    else:
        try:
            reply_text = brain.reply(content, history=convo, sender="chef") or ""
        except Exception:
            logger.exception("Lumina brain reply failed")
            reply_text = "…(thinking failed — my backend hiccuped. Say that again?)"
        if not reply_text.strip():
            reply_text = "…(thinking failed — I came back empty. Try once more?)"

    # 4. Persist + return her reply — linked back to the user turn (and thread).
    #    PQC Q5: if the conversation negotiated hybrid AND the operator published
    #    a prekey, seal the reply so the app opens it hybrid-pq. Otherwise the
    #    plaintext reply is stored unchanged (classical path).
    reply_wire = reply_text
    if convo_is_hybrid:
        sealed = _seal_hybrid_outbound(reply_text, recipient_short="chef")
        if sealed is not None:
            reply_wire = sealed
    reply_msg = _persist(
        hist,
        LUMINA_URI,
        OPERATOR_ID,
        reply_wire,
        reply_to_id=user_msg.id,
        thread_id=thread_id,
    )

    # Web clients (the legacy webui) refresh on a ws "new" ping if available.
    try:
        from skchat import webui as _webui

        await _webui._ws_broadcast({"type": "new"})
    except Exception:
        logger.debug("ws broadcast unavailable", exc_info=True)

    return JSONResponse(
        {
            "ok": True,
            "id": user_msg.id,
            "recipient": LUMINA_ID,
            "ts": user_msg.timestamp.isoformat(),
            # Full shared contract (+ legacy fields) so the app round-trips it.
            "reply": _msg_to_app(reply_msg, self_id=OPERATOR_ID),
        }
    )


@router.post("/v1/react")
async def api_react(request: Request):
    """Add or remove an emoji reaction on a message.

    Body: ``{conversation_id, message_id, emoji, op: "add"|"remove",
    sender?}``. Returns the updated message in the full contract. The operator
    is the default reactor when ``sender`` is omitted.
    """
    try:
        body = await request.json()
    except Exception:
        body = {}
    message_id = (body.get("message_id") or "").strip()
    emoji = (body.get("emoji") or "").strip()
    op = (body.get("op") or "add").strip().lower()
    sender = (body.get("sender") or OPERATOR_ID).strip()
    if not message_id or not emoji:
        raise HTTPException(400, "message_id and emoji are required")
    if op not in ("add", "remove"):
        raise HTTPException(400, "op must be 'add' or 'remove'")

    hist = _get_history()
    if op == "add":
        msg = hist.set_reaction(message_id, emoji, sender)
    else:
        msg = hist.clear_reaction(message_id, emoji, sender)
    if msg is None:
        raise HTTPException(404, "message not found")
    return JSONResponse({"ok": True, "message": _msg_to_app(msg, self_id=OPERATOR_ID)})


@router.post("/v1/edit")
async def api_edit(request: Request):
    """Edit a message body (archives the prior body, stamps edited_at).

    Body: ``{message_id, body}``. Enforces the 24h server-side edit window —
    an out-of-window edit returns 403. Returns the updated message.
    """
    try:
        body = await request.json()
    except Exception:
        body = {}
    message_id = (body.get("message_id") or "").strip()
    new_body = body.get("body")
    if new_body is None:
        new_body = body.get("content")
    if not message_id:
        raise HTTPException(400, "message_id is required")
    if not (new_body or "").strip():
        raise HTTPException(400, "body cannot be empty")

    hist = _get_history()
    try:
        msg = hist.edit_message(message_id, new_body)
    except ValueError as exc:
        # 24h window elapsed (or empty body) — refuse, don't 500.
        raise HTTPException(403, str(exc))
    if msg is None:
        raise HTTPException(404, "message not found")
    return JSONResponse({"ok": True, "message": _msg_to_app(msg, self_id=OPERATOR_ID)})


@router.post("/v1/receipt")
async def api_receipt(request: Request):
    """Record a delivery/read receipt.

    Body: ``{conversation_id, message_id, kind: "delivered"|"read", sender?}``.
    Idempotent. Returns the updated message.
    """
    try:
        body = await request.json()
    except Exception:
        body = {}
    message_id = (body.get("message_id") or "").strip()
    kind = (body.get("kind") or "").strip().lower()
    sender = (body.get("sender") or OPERATOR_ID).strip()
    if not message_id:
        raise HTTPException(400, "message_id is required")
    if kind not in ("delivered", "read"):
        raise HTTPException(400, "kind must be 'delivered' or 'read'")

    hist = _get_history()
    msg = hist.record_receipt(message_id, kind, sender)
    if msg is None:
        raise HTTPException(404, "message not found")
    return JSONResponse({"ok": True, "message": _msg_to_app(msg, self_id=OPERATOR_ID)})


@router.get("/v1/thread/{thread_id}")
async def api_thread(thread_id: str):
    """Return all messages in a thread, oldest-first, in the full contract."""
    hist = _get_history()
    try:
        msgs = hist.get_thread(thread_id, limit=500)
    except Exception:
        logger.exception("thread load failed for %s", thread_id)
        msgs = []
    return JSONResponse(
        {
            "thread_id": thread_id,
            "messages": [_msg_to_app(m, self_id=OPERATOR_ID) for m in msgs],
        }
    )


@router.post("/v1/presence")
async def api_presence():
    return JSONResponse({"ok": True})


@router.get("/")
async def api_root():
    return JSONResponse({"status": "ok", "service": "skchat-daemon-proxy"})


@router.get("/v1/webrtc/ice-config")
async def api_ice_config():
    try:
        from skchat.connectivity import ice_config

        cfg = ice_config("lumina@chef.skworld", "guest", {})
        return JSONResponse(cfg.get("ice_servers", []))
    except Exception:
        return JSONResponse([])


@router.get("/v1/webrtc/peers")
async def api_webrtc_peers():
    return JSONResponse([])


@router.post("/v1/access/token")
async def api_access_token(request: Request):
    """Proxy the capauth access-token mint to skcomms-api (:9384) so the web
    app (served same-origin from the webui) can reach it for the skos Ops
    surfaces. The daemon holds the PGP key; the app only gets the signed token."""
    import json
    import urllib.error
    import urllib.request

    body = await request.body()
    req = urllib.request.Request(
        f"{_SKCOMMS_API}/api/v1/access/token",
        data=body,
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    try:
        r = urllib.request.urlopen(req, timeout=10)
        return JSONResponse(json.loads(r.read()))
    except urllib.error.HTTPError as e:
        try:
            payload = json.loads(e.read() or b"{}")
        except Exception:
            payload = {"detail": "mint error"}
        return JSONResponse(payload, status_code=e.code)
    except Exception as exc:
        logger.warning("access-token mint proxy failed: %s", exc)
        raise HTTPException(502, f"mint backend unavailable: {exc}")
