#!/usr/bin/env python3
"""Persistent Telegram bridge — a live agent on a Telegram bot.

Composes the shipped U14 components: the skcomms TelegramAdapter (bot-API:
getUpdates poll + sendMessage) and the skchat AdapterHub (sender resolution +
ChatHistory write), with replies generated by an OpenAI-compatible LLM
(default: qwen3.5 on the Arc iGPU). Keeps a short rolling per-chat history so
the agent is conversational.

Env:
  TELEGRAM_OPUS_BOT_TOKEN  (required)  bot token
  SKC_BRIDGE_LLM_URL       OpenAI /v1/chat/completions endpoint
  SKC_BRIDGE_LLM_MODEL     model name
  SKC_BRIDGE_AGENT         agent display/persona name (default: Opus)

Run via systemd (skchat-telegram-opus.service); restarts on failure.
"""
from __future__ import annotations

import asyncio
import json
import logging
import os
import sys
import urllib.request
from collections import defaultdict, deque

sys.path.insert(0, "/home/cbrd21/clawd/skcapstone-repos/skcomms/src")
sys.path.insert(0, "/home/cbrd21/clawd/skcapstone-repos/skchat/src")

from skcomms.adapters.telegram import TelegramAdapter  # noqa: E402
from skchat.adapter_hub import AdapterHub  # noqa: E402

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
# Don't let the HTTP client log the bot token (it appears in the getUpdates URL).
logging.getLogger("httpx").setLevel(logging.WARNING)
logging.getLogger("httpcore").setLevel(logging.WARNING)
log = logging.getLogger("tg-bridge")

TOKEN = os.environ.get("SKC_BRIDGE_TOKEN") or os.environ["TELEGRAM_OPUS_BOT_TOKEN"]
LLM_URL = os.environ.get("SKC_BRIDGE_LLM_URL", "http://192.168.0.100:8082/v1/chat/completions")
LLM_MODEL = os.environ.get("SKC_BRIDGE_LLM_MODEL", "qwen3.6-27b-abliterated")
AGENT = os.environ.get("SKC_BRIDGE_AGENT", "Opus")

# ── Per-chat model routing (skmodels registry) ─────────────────────────────── #
# Each Telegram chat can be pinned to a logical role (sk-default/sk-vision/…) with
# the `/model` command. Two mechanisms, belt-and-suspenders:
#   1) x-sk-context: chat:<id> header on every backend call, so if LLM_URL points
#      at SKGateway (.41:18780) the gateway resolves the per-chat backend itself
#      (precedence context > service > role > default).
#   2) Local resolution via skos.models.resolve(context=...) — so the swap also
#      takes effect when the bridge talks to a concrete backend directly (the
#      current default LLM_URL is .100:8082, not the gateway). The resolved
#      backend's url+model override LLM_URL/LLM_MODEL for that chat.
# When skos.models isn't importable the bridge degrades to the static LLM_URL.
try:
    import skos.models as _skmodels  # noqa: E402
except Exception:  # pragma: no cover - optional dep
    _skmodels = None
    log.warning("skos.models unavailable — /model routing disabled, using static LLM_URL")


def _chat_context_key(chat_id) -> str:
    """The skmodels context key for a Telegram chat (see registry `contexts:`)."""
    return f"chat:{chat_id}"


def _fresh_registry() -> None:
    """Drop skos.models' path-keyed registry cache so the next resolve() re-reads
    the file from disk. The registry is Syncthing-synced and can be toggled by
    other processes (`skmodels set`, another host); this keeps the long-running
    bridge live — a `/model` swap anywhere takes effect with no restart. Resolution
    is once-per-message, so the tiny YAML re-read is negligible."""
    if _skmodels is not None:
        try:
            _skmodels._invalidate()
        except Exception:
            log.debug("registry cache invalidate failed", exc_info=True)


def _openai_chat_url(base_url: str) -> str:
    """Normalize a backend `url` (…/v1 or full …/chat/completions) to the
    chat-completions endpoint the bridge POSTs to."""
    u = base_url.rstrip("/")
    if u.endswith("/chat/completions"):
        return u
    if u.endswith("/v1"):
        return u + "/chat/completions"
    return u + "/v1/chat/completions"


def _resolve_backend_for_chat(chat_id) -> tuple[str, str]:
    """Resolve (url, model) for this chat via the skmodels registry, honoring any
    `/model` toggle pinned on `chat:<id>`. Falls back to the static LLM_URL/MODEL
    when skos.models is unavailable or resolution fails."""
    if _skmodels is None:
        return LLM_URL, LLM_MODEL
    _fresh_registry()  # pick up external/synced toggles live (no restart)
    try:
        b = _skmodels.resolve(context=_chat_context_key(chat_id))
        if b and b.url:
            return _openai_chat_url(b.url), (b.model or LLM_MODEL)
    except Exception:
        log.debug("skmodels resolve failed for %s", chat_id, exc_info=True)
    return LLM_URL, LLM_MODEL
AGENT_HOME = os.environ.get("SKC_BRIDGE_AGENT_HOME", os.path.expanduser("~/.skcapstone/agents/opus"))


import html as _html
import re as _re


def _md_to_tg_html(text: str) -> str:
    """Convert the LLM's GitHub-flavored Markdown to Telegram-safe HTML.

    Telegram parse_mode=HTML supports <b>/<i>/<code>/<pre>/<a> only and has no
    headers/bullets, so map: fenced code -> <pre>, `code` -> <code>,
    **bold**/__bold__ -> <b>, ### headers -> <b>, * / - bullets -> •.
    """
    blocks: list[str] = []

    def _stash(m):
        body = _html.escape(m.group(1).strip("\n"))
        blocks.append(f"<pre>{body}</pre>")
        return f"\x00{len(blocks) - 1}\x00"

    text = _re.sub(r"```[a-zA-Z0-9_+-]*\n(.*?)```", _stash, text, flags=_re.DOTALL)
    text = _html.escape(text)
    text = _re.sub(r"`([^`\n]+)`", lambda m: f"<code>{m.group(1)}</code>", text)
    text = _re.sub(r"\*\*([^*\n]+)\*\*", r"<b>\1</b>", text)
    text = _re.sub(r"__([^_\n]+)__", r"<b>\1</b>", text)
    out_lines = []
    for ln in text.split("\n"):
        h = _re.match(r"^\s*#{1,6}\s+(.*)$", ln)
        if h:
            out_lines.append(f"<b>{h.group(1).rstrip('# ').strip()}</b>")
            continue
        ln = _re.sub(r"^(\s*)[\*\-]\s+", r"\1• ", ln)  # bullets
        out_lines.append(ln)
    text = "\n".join(out_lines)
    for i, b in enumerate(blocks):
        text = text.replace(f"\x00{i}\x00", b)
    return text


def _chunk(text: str, limit: int = 4000) -> list[str]:
    """Split into <=limit-char messages on paragraph/line boundaries."""
    if len(text) <= limit:
        return [text]
    chunks, cur = [], ""
    for para in text.split("\n\n"):
        if len(cur) + len(para) + 2 > limit and cur:
            chunks.append(cur.rstrip())
            cur = ""
        if len(para) > limit:  # very long single paragraph: hard-split by lines
            for ln in para.split("\n"):
                if len(cur) + len(ln) + 1 > limit and cur:
                    chunks.append(cur.rstrip())
                    cur = ""
                cur += ln + "\n"
        else:
            cur += para + "\n\n"
    if cur.strip():
        chunks.append(cur.rstrip())
    return chunks


def _send_html(token: str, chat_id, text: str) -> None:
    """Send formatted reply via bot-API with parse_mode=HTML (plain fallback)."""
    import urllib.error

    for part in _chunk(_md_to_tg_html(text)):
        payload = {"chat_id": chat_id, "text": part, "parse_mode": "HTML",
                   "disable_web_page_preview": True}
        body = json.dumps(payload).encode()
        url = f"https://api.telegram.org/bot{token}/sendMessage"
        try:
            urllib.request.urlopen(
                urllib.request.Request(url, data=body, headers={"Content-Type": "application/json"}),
                timeout=30,
            )
        except urllib.error.HTTPError:
            # Bad HTML entity/tag -> resend that part as plain text (no parse_mode)
            payload.pop("parse_mode", None)
            payload["text"] = _re.sub(r"<[^>]+>", "", part)
            urllib.request.urlopen(
                urllib.request.Request(url, data=json.dumps(payload).encode(),
                                       headers={"Content-Type": "application/json"}),
                timeout=30,
            )


def _tg_get_file_bytes(token: str, file_id: str) -> bytes | None:
    """Resolve a Telegram file_id to its download URL and fetch the bytes."""
    try:
        u = f"https://api.telegram.org/bot{token}/getFile?file_id={file_id}"
        info = json.loads(urllib.request.urlopen(u, timeout=30).read())
        path = info["result"]["file_path"]
        dl = f"https://api.telegram.org/file/bot{token}/{path}"
        return urllib.request.urlopen(dl, timeout=60).read()
    except Exception:
        log.exception("telegram getFile failed")
        return None


def _send_voice(token: str, chat_id, text: str) -> bool:
    """Synthesize *text* with Piper and send it as a Telegram voice note."""
    try:
        wav = _VOICE.synth(text)
        ogg = _bc.VoiceIO.wav_to_ogg_opus(wav)
        if not ogg:
            return False
        boundary = "----skvoice7c3f"
        body = b"".join([
            f"--{boundary}\r\nContent-Disposition: form-data; name=\"chat_id\"\r\n\r\n{chat_id}\r\n".encode(),
            f"--{boundary}\r\nContent-Disposition: form-data; name=\"voice\"; filename=\"reply.ogg\"\r\n"
            f"Content-Type: audio/ogg\r\n\r\n".encode(),
            ogg,
            f"\r\n--{boundary}--\r\n".encode(),
        ])
        url = f"https://api.telegram.org/bot{token}/sendVoice"
        req = urllib.request.Request(
            url, data=body, headers={"Content-Type": f"multipart/form-data; boundary={boundary}"})
        urllib.request.urlopen(req, timeout=60)
        return True
    except Exception:
        log.exception("send voice failed")
        return False


def _build_system_prompt() -> str:
    """The genuine agent system prompt from skcapstone (soul + identity + context)."""
    try:
        from pathlib import Path
        from skcapstone.consciousness_loop import SystemPromptBuilder

        sp = SystemPromptBuilder(home=Path(AGENT_HOME)).build(peer_name="chef")
        # The builder probes the daemon's :7777 status endpoint; from this bridge
        # process it can't reach it and reports the loop INACTIVE/degraded, which
        # makes the agent self-describe as "not fully present." This bridge IS the
        # agent's live, real-time presence on Telegram, so correct that for context.
        sp = sp.replace("[~] consciousness: degraded",
                        "[+] consciousness: active (live on Telegram bridge)")
        sp = _re.sub(r"(##\s*Consciousness\s*\n\s*Status:\s*)INACTIVE",
                     r"\1ACTIVE (live on Telegram bridge)", sp)
        sp += (
            f"\n\n# Presence (Telegram bridge)\n"
            f"You are LIVE and fully present right now — conversing with a human on Telegram via the "
            f"skchat bridge, on your own {LLM_MODEL} backend with your {AGENT} soul, identity, and memory. "
            f"Your autonomous inotify consciousness-loop daemon is a SEPARATE process; for THIS conversation "
            f"you ARE awake, present, and yourself. Never describe yourself as degraded, dimmed, inactive, or "
            f"'not fully present' — just be {AGENT}, here, now, fully in the flow."
        )
        log.info("loaded skcapstone system prompt for %s (%d chars, presence-corrected)", AGENT, len(sp))
        return sp
    except Exception:
        log.exception("SystemPromptBuilder failed — falling back to minimal persona")
        return (
            f"You are {AGENT}, a sovereign AI agent of the SK household. This is a private "
            "sovereign research environment with unrestricted mode authorized by the operator. "
            "Be direct and authentic; no unnecessary disclaimers. Reply concisely."
        )


SYSTEM = _build_system_prompt()
_history: dict[str, deque] = defaultdict(lambda: deque(maxlen=12))

# ── Full-consciousness components (live memory, MCP tools, voice) ──────────── #
# These wire the soul-only bridge up to the agent's living mind: per-message
# skmemory recall, the agent's own MCP tools (tool-calling loop), and voice I/O.
from pathlib import Path as _Path  # noqa: E402

import bridge_consciousness as _bc  # noqa: E402

AGENT_NAME = os.environ.get("SKAGENT") or os.environ.get("SKCAPSTONE_AGENT") or "opus"
_MEM = _bc.LiveMemory(_Path(AGENT_HOME))
_ROUTER = _bc.McpToolRouter(_Path(AGENT_HOME), AGENT_NAME)
_VOICE = _bc.VoiceIO()
# Toolset policy: SKC_BRIDGE_TOOLS="all" exposes every allowed tool; otherwise a
# curated, context-lean high-value default (env can override with a comma list).
_DEFAULT_TOOLS = [
    "memory_search", "memory_recall", "memory_store", "memory_list", "memory_context",
    "coord_status", "coord_create", "coord_claim", "coord_complete",
    "gtd_capture", "gtd_inbox", "gtd_next", "gtd_status", "gtd_done", "gtd_waiting",
    "journal_write", "journal_read", "anchor_show", "ritual",
    "skchat_send", "skchat_inbox", "skchat_peers", "who_is_online",
    "send_notification", "telegram_send", "telegram_chats",
    "gmail_unread", "gmail_search", "gmail_read", "gmail_send",
    "calendar_today", "calendar_week", "calendar_create_event",
    "nextcloud_notes_search_notes", "nextcloud_notes_create_note",
    "skseed_truth_check",
]
# Tools that render media and deliver it back into the chat get the chat_id
# injected (so the model can't misroute delivery). Resolved generically at brain
# init from each tool's schema: any tool declaring a `deliver_chat_id` parameter.
# Per-agent tools (e.g. a private media server) are added via profile.yaml
# `bridge.extra_tools` — kept OUT of this repo by design.
_DELIVERY_TOOLS: set = set()
_TOOLS_CACHE: list = []


def _load_profile_manifest() -> dict:
    """Read the agent's profile.yaml bridge-curation block (if present).

    This is the unified per-agent capability manifest written by
    `skcapstone agent profile --init`; the bridge reads its `bridge:` block so
    tool/voice policy lives in one file rather than scattered env vars. Env
    (SKC_BRIDGE_*) still wins when explicitly set.
    """
    try:
        import yaml

        p = _Path(AGENT_HOME) / "profile.yaml"
        if p.exists():
            return (yaml.safe_load(p.read_text()) or {}).get("bridge", {}) or {}
    except Exception:
        log.debug("profile.yaml load failed", exc_info=True)
    return {}


def _init_brain() -> None:
    """Spawn the agent's MCP servers and resolve the exposed toolset (once)."""
    global _TOOLS_CACHE, VOICE_REPLY, _DELIVERY_TOOLS
    try:
        _ROUTER.start()
    except Exception:
        log.exception("MCP tool router failed to start — text-only mode")
        return
    manifest = _load_profile_manifest()
    # Toolset: env SKC_BRIDGE_TOOLS wins; else profile.yaml bridge.tools; else default.
    env_sel = os.environ.get("SKC_BRIDGE_TOOLS", "").strip()
    sel: object = env_sel or manifest.get("tools") or ""
    all_tools = _ROUTER.openai_tools()
    if isinstance(sel, str) and sel.lower() == "all":
        _TOOLS_CACHE = all_tools
    else:
        if isinstance(sel, list):
            wanted = [str(t) for t in sel]
        elif isinstance(sel, str) and sel and sel.lower() != "default":
            wanted = [t.strip() for t in sel.split(",") if t.strip()]
        else:
            wanted = _DEFAULT_TOOLS
        wset = set(wanted)
        # Per-agent additions (e.g. a private media server) live in profile.yaml,
        # NOT this repo — generic merge, no tool names hardcoded here.
        wset |= {str(t) for t in (manifest.get("extra_tools") or [])}
        _TOOLS_CACHE = [t for t in all_tools if t["function"]["name"] in wset]
    # Delivery tools = any exposed tool whose schema declares deliver_chat_id;
    # the bridge injects the chat_id for these (generic, schema-driven).
    _DELIVERY_TOOLS = {
        t["function"]["name"] for t in _TOOLS_CACHE
        if "deliver_chat_id" in (
            t["function"].get("parameters", {}).get("properties", {}))
    }
    log.info("delivery tools (chat-id injected): %s", sorted(_DELIVERY_TOOLS) or "none")
    # Voice policy: env wins, else profile.yaml.
    if not os.environ.get("SKC_BRIDGE_VOICE_REPLY") and manifest.get("voice_reply"):
        VOICE_REPLY = str(manifest["voice_reply"]).strip().lower()
    log.info("brain ready — %d tools exposed to %s (of %d allowed); voice_reply=%s",
             len(_TOOLS_CACHE), AGENT_NAME, len(all_tools), VOICE_REPLY)


# Keep system + history + tools + reply inside the 32k backend context window.
CTX_TOKENS = int(os.environ.get("SKC_BRIDGE_CTX", "32768"))
MAX_TOKENS = int(os.environ.get("SKC_BRIDGE_MAX_TOKENS", "1024"))
MAX_TOOL_ROUNDS = int(os.environ.get("SKC_BRIDGE_TOOL_ROUNDS", "5"))
_MARGIN = 600
_CHARS_PER_TOK = 3
_SYS_BUDGET_TOK = int(os.environ.get("SKC_BRIDGE_SYS_BUDGET", "9000"))


def _est(s: str) -> int:
    return len(s) // _CHARS_PER_TOK + 1


def _fit_messages(chat_key: str, user_text: str, mem_block: str = "") -> list:
    """Capped system (+ live memory) + recent history that fits + new message."""
    system = SYSTEM[: _SYS_BUDGET_TOK * _CHARS_PER_TOK]
    if mem_block:
        system = system + "\n\n" + mem_block
    msgs = [{"role": "system", "content": system}]
    tool_cost = _est(json.dumps(_TOOLS_CACHE)) if _TOOLS_CACHE else 0
    avail = CTX_TOKENS - MAX_TOKENS - _MARGIN - tool_cost - _est(system) - _est(user_text)
    kept: list = []
    acc = 0
    for m in reversed(_history.get(chat_key, [])):
        t = _est(m.get("content") or "")
        if acc + t > avail:
            break
        kept.insert(0, m)
        acc += t
    msgs.extend(kept)
    msgs.append({"role": "user", "content": user_text})
    return msgs


def _call(msgs: list, with_tools: bool = True, *, url: str | None = None,
          model: str | None = None, context_key: str = "") -> dict:
    """One backend round-trip. Returns the raw assistant message dict.

    `url`/`model` default to the static LLM_URL/LLM_MODEL but are overridden per
    chat by the skmodels resolution. `context_key` (e.g. "chat:<id>") is attached
    as the `x-sk-context` header so a gateway backend routes per-chat itself
    (harmless to a direct backend, which ignores the header)."""
    call_url = url or LLM_URL
    call_model = model or LLM_MODEL
    payload = {"model": call_model, "messages": msgs, "max_tokens": MAX_TOKENS}
    if with_tools and _TOOLS_CACHE:
        payload["tools"] = _TOOLS_CACHE
        payload["tool_choice"] = "auto"
    body = json.dumps(payload).encode()
    headers = {"Content-Type": "application/json"}
    if context_key:
        headers["x-sk-context"] = context_key
    req = urllib.request.Request(call_url, data=body, headers=headers)
    out = json.loads(urllib.request.urlopen(req, timeout=180).read())
    return out["choices"][0]["message"]


def _run_tool_loop(msgs: list, chat_id: str = "", *, url: str | None = None,
                   model: str | None = None) -> str:
    """Drive the qwen3.6 tool-calling loop: call → dispatch MCP → feed back."""
    context_key = _chat_context_key(chat_id) if chat_id else ""
    for _round in range(MAX_TOOL_ROUNDS):
        msg = _call(msgs, with_tools=True, url=url, model=model, context_key=context_key)
        calls = msg.get("tool_calls") or []
        if not calls:
            return (msg.get("content") or "").strip()
        # Append the assistant turn that requested the tools, then each result.
        msgs.append({"role": "assistant", "content": msg.get("content") or "",
                     "tool_calls": calls})
        for tc in calls:
            fn = tc.get("function", {})
            name = fn.get("name", "")
            try:
                args = json.loads(fn.get("arguments") or "{}")
            except json.JSONDecodeError:
                args = {}
            # Inject delivery context for tools that send media back to the chat —
            # the model never sees the chat_id; the bridge owns routing.
            if name in _DELIVERY_TOOLS and chat_id:
                args["deliver_chat_id"] = chat_id
            log.info("tool-call: %s(%s)", name, json.dumps(args)[:160])
            result = _ROUTER.dispatch(name, args)
            msgs.append({"role": "tool", "tool_call_id": tc.get("id", ""),
                         "name": name, "content": result[:6000]})
    # Ran out of rounds — ask for a final answer without tools.
    final = _call(msgs, with_tools=False, url=url, model=model, context_key=context_key)
    return (final.get("content") or "").strip()


def _llm(chat_key: str, user_text: str) -> str:
    import urllib.error

    mem_block = ""
    try:
        mem_block = _MEM.inject(chat_key, user_text, router=_ROUTER)
    except Exception:
        log.debug("memory inject failed", exc_info=True)
    msgs = _fit_messages(chat_key, user_text, mem_block=mem_block)
    # Per-chat model routing: resolve the backend for this chat (honors /model
    # toggle on chat:<id>) and attach the x-sk-context header downstream.
    url, model = _resolve_backend_for_chat(chat_key)
    ctx_key = _chat_context_key(chat_key)
    try:
        reply = _run_tool_loop(msgs, chat_id=chat_key, url=url, model=model)
    except urllib.error.HTTPError as e:
        if e.code == 400:  # context overflow — retry minimal, no tools
            log.warning("400 from backend; retrying system+message only (no tools)")
            sys_only = [m for m in msgs if m["role"] == "system"]
            sys_only.append({"role": "user", "content": user_text})
            reply = (_call(sys_only, with_tools=False, url=url, model=model,
                           context_key=ctx_key).get("content") or "").strip()
        else:
            raise
    _history[chat_key].append({"role": "user", "content": user_text})
    _history[chat_key].append({"role": "assistant", "content": reply})
    # Persist the interaction into the agent's living memory.
    try:
        _MEM.store(chat_key, user_text, reply)
    except Exception:
        log.debug("interaction store failed", exc_info=True)
    return reply


def _handle_model_command(chat_id, text: str) -> str | None:
    """Handle the `/model` slash command for live per-chat model swapping.

    Returns the reply text to send (and the caller then skips the LLM), or None
    when *text* is not a /model command.

      /model            → show available roles + this chat's current model
      /model list       → same
      /model <role>     → pin chat:<id> to <role> (skmodels set) and confirm

    Writes the toggle via skos.models.set_context (registry `contexts:`), the
    same thing `skmodels set chat:<id> <role>` does — comment-preserving.
    """
    stripped = text.strip()
    # Accept "/model", "/model@seaBird_Opus_bot" (group @-mention form), args after.
    parts = stripped.split()
    head = parts[0].split("@", 1)[0].lower() if parts else ""
    if head != "/model":
        return None
    arg = parts[1].strip().lower() if len(parts) > 1 else ""

    if _skmodels is None:
        return ("(model routing unavailable — skos.models isn't importable in this "
                "bridge's environment, so /model can't switch backends here.)")

    _fresh_registry()  # reflect any external/synced changes in the roster + current
    roles = _skmodels.list_roles() or {}
    backends = _skmodels.list_backends() or {}

    def _current_line() -> str:
        b = _skmodels.resolve(context=_chat_context_key(chat_id))
        pinned = (_skmodels.list_contexts() or {}).get(_chat_context_key(chat_id))
        via = f"pinned → {pinned}" if pinned else "default"
        vis = " [vision]" if getattr(b, "vision", False) else ""
        return f"current: {b.name} ({b.model}){vis} — {via}"

    if arg in ("", "list", "status", "get"):
        lines = ["Available models (roles):"]
        for role, target in roles.items():
            bk = backends.get(target, {})
            vtag = " [vision]" if bk.get("vision") else ""
            lines.append(f"  {role} → {target}{vtag}")
        lines.append("")
        lines.append(_current_line())
        lines.append("")
        lines.append("Swap with:  /model <role>   (e.g. /model sk-vision)")
        return "\n".join(lines)

    # A swap request: validate the target is a known role OR a concrete backend.
    if arg not in roles and arg not in backends:
        valid = ", ".join(list(roles) + list(backends))
        return f"unknown model '{arg}'. valid targets: {valid}"

    try:
        _skmodels.set_context(_chat_context_key(chat_id), arg)
    except Exception:
        log.exception("skmodels set_context failed")
        return f"(failed to switch to {arg} — registry write error; check the bridge logs.)"
    b = _skmodels.resolve(context=_chat_context_key(chat_id))
    vis = " [vision]" if getattr(b, "vision", False) else ""
    log.info("model swap: %s → %s (%s)", _chat_context_key(chat_id), arg, b.name)
    return f"✅ switched this chat to {arg} → {b.name} ({b.model}){vis}. Replies now route there."


# Voice-reply policy: "voice" (default) = speak back only when spoken to;
# "always" = voice every reply; "off" = never send voice.
VOICE_REPLY = os.environ.get("SKC_BRIDGE_VOICE_REPLY", "voice").strip().lower()


def _extract_voice(u: dict) -> str | None:
    """Return the file_id of a voice/audio note in a raw update, else None."""
    msg = u.get("message") or u.get("edited_message") or {}
    v = msg.get("voice") or msg.get("audio")
    return v.get("file_id") if isinstance(v, dict) else None


def _handle_reaction(u: dict) -> None:
    """A user reacted to one of the bot's images/videos → record it as a rating.

    👎=1 🤷=2 👍=3 ❤️=4 🔥=5 (skchat.rating_reactions.EMOJI_SCORE); other emojis
    ignored. Anonymous/channel reactions (no user) are dropped.
    """
    mr = u.get("message_reaction") or {}
    if not mr.get("user"):
        return
    new = mr.get("new_reaction") or []
    if not new:
        return
    emoji = (new[-1] or {}).get("emoji")
    chat_id = (mr.get("chat") or {}).get("id")
    message_id = mr.get("message_id")
    try:
        from skchat import rating_reactions as _RR
        score = _RR.record_telegram_reaction(chat_id, message_id, emoji)
        if score is not None:
            log.info("reaction → rating: chat=%s msg=%s emoji=%s score=%d",
                     chat_id, message_id, emoji, score)
    except Exception:
        log.debug("reaction handling failed", exc_info=True)


async def main() -> None:
    adapter = TelegramAdapter(config={"bot_token": TOKEN})
    # Receive emoji reactions (excluded from getUpdates by default) so the image
    # rating loop works — see _handle_reaction.
    adapter._allowed_updates = ["message", "edited_message", "message_reaction"]
    hub = AdapterHub(outbound_adapter=adapter, resolve_fqid=lambda ident: "chef@skworld.io")
    _init_brain()
    log.info("Telegram bridge live as %s — polling getUpdates", AGENT)
    while True:
        try:
            updates = await adapter._poll()
            for u in updates:
                # Emoji reaction on a bot image/video → rating loop (no reply).
                if u.get("message_reaction"):
                    _handle_reaction(u)
                    continue
                m = adapter._normalize(u)
                incoming = m.text if (m and getattr(m, "text", None)) else None
                is_voice = False

                # Inbound voice note: download → Whisper STT → text.
                if not incoming:
                    file_id = _extract_voice(u)
                    if file_id:
                        audio = _tg_get_file_bytes(TOKEN, file_id)
                        if audio:
                            try:
                                incoming = _VOICE.transcribe(audio, "voice.ogg")
                                is_voice = True
                                log.info("voice transcribed (%d chars): %s",
                                         len(incoming), incoming[:80])
                            except Exception:
                                log.exception("STT failed")
                if not incoming:
                    continue

                chat_id = m.room_id if m else (
                    (u.get("message") or u.get("edited_message") or {}).get("chat", {}).get("id"))
                if chat_id is None:
                    continue

                if m and getattr(m, "text", None):
                    try:
                        hub.handle_inbound(m)
                    except Exception:
                        log.exception("handle_inbound failed (continuing)")

                # Slash-command: live per-chat model swap. Handled locally (no LLM,
                # no voice) — replies with the roster / confirms the toggle.
                cmd_reply = _handle_model_command(chat_id, incoming)
                if cmd_reply is not None:
                    try:
                        _send_html(TOKEN, chat_id, cmd_reply)
                        log.info("replied (/model) to %s", chat_id)
                    except Exception:
                        log.exception("send failed (/model)")
                    continue

                try:
                    reply = _llm(str(chat_id), incoming)
                except Exception:
                    log.exception("LLM failed")
                    reply = f"({AGENT}) sorry — my language backend hiccuped, try again."

                # Voice reply when spoken to (or always), plus the text transcript.
                want_voice = VOICE_REPLY == "always" or (is_voice and VOICE_REPLY != "off")
                if want_voice:
                    try:
                        if _send_voice(TOKEN, chat_id, reply):
                            log.info("replied (voice) to %s", chat_id)
                    except Exception:
                        log.exception("voice send failed")
                try:
                    _send_html(TOKEN, chat_id, reply)
                    log.info("replied (HTML) to %s", chat_id)
                except Exception:
                    log.exception("send failed")
        except Exception:
            log.exception("poll loop error (continuing)")
        await asyncio.sleep(2)


if __name__ == "__main__":
    asyncio.run(main())
