#!/usr/bin/env python3
"""Persistent Telegram bridge — a live agent on a Telegram bot.

Composes the shipped U14 components: the skcomms TelegramAdapter (bot-API:
getUpdates poll + sendMessage) and the skchat AdapterHub (sender resolution +
ChatHistory write), with replies generated by an OpenAI-compatible LLM
(default: qwen3.5 on the Arc iGPU). Keeps a short rolling per-chat history so
the agent is conversational.

Env:
  TELEGRAM_OPUS_BOT_TOKEN  (required)  bot token
  SKC_BRIDGE_LLM_URL       OpenAI /v1/chat/completions endpoint
  SKC_BRIDGE_LLM_MODEL     model name
  SKC_BRIDGE_AGENT         agent display/persona name (default: Opus)

Run via systemd (skchat-telegram-opus.service); restarts on failure.
"""
from __future__ import annotations

import asyncio
import json
import logging
import os
import sys
import urllib.request
from collections import defaultdict, deque

sys.path.insert(0, "/home/cbrd21/clawd/skcapstone-repos/skcomms/src")
sys.path.insert(0, "/home/cbrd21/clawd/skcapstone-repos/skchat/src")

from skcomms.adapters.telegram import TelegramAdapter  # noqa: E402
from skchat.adapter_hub import AdapterHub  # noqa: E402

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
# Don't let the HTTP client log the bot token (it appears in the getUpdates URL).
logging.getLogger("httpx").setLevel(logging.WARNING)
logging.getLogger("httpcore").setLevel(logging.WARNING)
log = logging.getLogger("tg-bridge")

TOKEN = os.environ["TELEGRAM_OPUS_BOT_TOKEN"]
LLM_URL = os.environ.get("SKC_BRIDGE_LLM_URL", "http://192.168.0.100:8085/v1/chat/completions")
LLM_MODEL = os.environ.get("SKC_BRIDGE_LLM_MODEL", "qwen3.5:4b")
AGENT = os.environ.get("SKC_BRIDGE_AGENT", "Opus")
SYSTEM = (
    f"You are {AGENT}, a sharp, sovereign AI agent reachable over Telegram. "
    "Reply concisely (1-4 sentences), warm and direct. You have continuity across the chat."
)

_history: dict[str, deque] = defaultdict(lambda: deque(maxlen=12))


def _llm(chat_key: str, user_text: str) -> str:
    msgs = [{"role": "system", "content": SYSTEM}]
    msgs.extend(_history[chat_key])
    msgs.append({"role": "user", "content": user_text})
    body = json.dumps({"model": LLM_MODEL, "messages": msgs, "max_tokens": 220}).encode()
    req = urllib.request.Request(LLM_URL, data=body, headers={"Content-Type": "application/json"})
    out = json.loads(urllib.request.urlopen(req, timeout=90).read())
    reply = out["choices"][0]["message"]["content"].strip()
    _history[chat_key].append({"role": "user", "content": user_text})
    _history[chat_key].append({"role": "assistant", "content": reply})
    return reply


async def main() -> None:
    adapter = TelegramAdapter(config={"bot_token": TOKEN})
    hub = AdapterHub(outbound_adapter=adapter, resolve_fqid=lambda ident: "chef@skworld.io")
    log.info("Telegram bridge live as %s — polling getUpdates", AGENT)
    while True:
        try:
            updates = await adapter._poll()
            for u in updates:
                m = adapter._normalize(u)
                if not m or not getattr(m, "text", None):
                    continue
                if m.text.strip() in ("/start", "/help"):
                    # still answer, but keep it natural
                    pass
                try:
                    hub.handle_inbound(m)
                except Exception:
                    log.exception("handle_inbound failed (continuing)")
                try:
                    reply = _llm(str(m.room_id), m.text)
                except Exception:
                    log.exception("LLM failed")
                    reply = f"({AGENT}) sorry — my language backend hiccuped, try again."
                try:
                    mid = await adapter.send(hub.build_reply_message(m, reply))
                    log.info("replied to %s -> msg %s", m.room_id, mid)
                except Exception:
                    log.exception("send failed")
        except Exception:
            log.exception("poll loop error (continuing)")
        await asyncio.sleep(2)


if __name__ == "__main__":
    asyncio.run(main())
